# Generated by Django 3.2.9 on 2023-03-14 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('betreff', models.CharField(max_length=70)),
                ('handy', models.IntegerField()),
                ('von', models.CharField(max_length=70)),
                ('nach', models.CharField(max_length=70)),
                ('abholzeit', models.CharField(max_length=70)),
                ('bestellzeit', models.CharField(default=datetime.datetime(2023, 3, 14, 15, 57, 48, 812057), max_length=70)),
                ('anmerkung', models.CharField(max_length=140)),
            ],
        ),
    ]
