# Generated by Django 3.2.9 on 2023-03-14 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('betreff', models.CharField(max_length=70)),
                ('handy', models.CharField(max_length=70)),
                ('von', models.CharField(max_length=70)),
                ('nach', models.CharField(max_length=70)),
                ('abholzeit', models.CharField(max_length=70)),
                ('bestellzeit', models.CharField(default=datetime.datetime(2023, 3, 14, 14, 0, 52, 283009), max_length=70)),
                ('anmerkung', models.CharField(max_length=140)),
            ],
        ),
    ]
