# Generated by Django 3.2.9 on 2023-03-14 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_anfrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anfrage',
            name='bestellzeit',
            field=models.CharField(default=datetime.datetime(2023, 3, 14, 15, 57, 48, 841847), max_length=70),
        ),
    ]
